"""empty message

Revision ID: 09598d3d0b4a
Revises: 1be7c8917c0e
Create Date: 2017-04-25 15:06:21.065110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09598d3d0b4a'
down_revision = '1be7c8917c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'book_data', ['title', 'author', 'pages'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_data', type_='unique')
    # ### end Alembic commands ###
