"""empty message

Revision ID: 1be7c8917c0e
Revises: 703d5792abcc
Create Date: 2017-04-25 15:03:41.938675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be7c8917c0e'
down_revision = '703d5792abcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'book_data', ['title', 'author'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_data', type_='unique')
    # ### end Alembic commands ###
