"""empty message

Revision ID: 3878c5c8fed3
Revises: 09598d3d0b4a
Create Date: 2017-04-25 15:26:25.878820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3878c5c8fed3'
down_revision = '09598d3d0b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_data_author', table_name='book_data')
    op.drop_index('ix_book_data_title', table_name='book_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_book_data_title', 'book_data', ['title'], unique=False)
    op.create_index('ix_book_data_author', 'book_data', ['author'], unique=False)
    # ### end Alembic commands ###
